package com.gempukku.lotro.logic.modifiers;

public enum ModifierEffect {
    SIGNET_MODIFIER, STRENGTH_MODIFIER,
    SKIRMISH_STRENGTH_EVALUATOR_MODIFIER,
    STRENGTH_BONUS_MODIFIER,
    VITALITY_MODIFIER, RESISTANCE_MODIFIER, SITE_NUMBER_MODIFIER, TWILIGHT_COST_MODIFIER, OVERWHELM_MODIFIER,
    WOUND_MODIFIER, BURDEN_MODIFIER, THREAT_MODIFIER, THREAT_LIMIT_MODIFIER,
    PRESENCE_MODIFIER, ARCHERY_MODIFIER, MOVE_LIMIT_MODIFIER, ACTION_MODIFIER, ASSIGNMENT_MODIFIER,
    DISCARD_FROM_PLAY_MODIFIER, DISCARD_NOT_FROM_PLAY, HINDERED_MODIFER,
    LOOK_OR_REVEAL_MODIFIER, SPOT_MODIFIER, TARGET_MODIFIER, RETURN_TO_HAND_MODIFIER, TRANSFER_MODIFIER,
    LIBERATION_MODIFIER, PAID_ASSIGNMENT_COST_MODIFIER,

    MOVE_TWILIGHT_MODIFIER,

    EXTRA_ACTION_MODIFIER, EXTRA_COST_MODIFIER, GAME_TEXT_DUPLICATE,
    INITIATIVE_MODIFIER, TEXT_MODIFIER,

    SPECIAL_FLAG_MODIFIER, REPLACE_SITE_MODIFIER, PLAY_SITE_MODIFIER,

    ADDITIONAL_CARD_TYPE, ADDITIONAL_CULTURE, ADDITIONAL_RACE, CAN_BEAR_EXTRA_ITEMS,

    REMOVE_KEYWORD_MODIFIER, GIVE_KEYWORD_MODIFIER, CANCEL_KEYWORD_BONUS_TARGET_MODIFIER, LOSE_ALL_KEYWORDS_MODIFIER,

    SANCTUARY_HEAL_MODIFIER, POTENTIAL_DISCOUNT_MODIFIER,

    STARTING_FELLOWSHIP_COST_MODIFIER,

    MINIMUM_BID_MODIFIER,

    HAND_REVEAL_MODIFIER,

    CANCEL_SKIRMISH_MODIFIER,

    UNIQUENESS_MODIFIER,

    DEAD_PILE_MODIFIER, SANCTUARY_REMOVE_BURDEN_MODIFIER
}
