package com.gempukku.lotro.logic.modifiers;

public enum ModifierFlag {
    HAS_TO_MOVE_IF_POSSIBLE,
    CANT_MOVE,
    RING_TEXT_INACTIVE,
    SARUMAN_FIRST_SENTENCE_INACTIVE,
    WIN_CHECK_AFTER_SHADOW_RECONCILE,
    CANT_PLAY_FROM_DISCARD_OR_DECK,
    CANT_TAKE_INTO_HAND_FROM_DISCARD_OR_DECK,
    EXTRA_CARD_TYPES_IN_STARTING_FELLOWSHIP,
    RING_BEARER_CANT_TAKE_THREAT_WOUNDS,
    SKIRMISH_ORDER_BY_FIRST_SHADOW_PLAYER,
    CANT_PREVENT_WOUNDS,
    CANT_TOUCH_CULTURE_TOKENS,
    TRANSFERS_FOR_FREE,
    SHADOW_PLAYER_REPLACED_CURRENT_SITE,
    REMOVE_CARDS_GOING_TO_DISCARD,
    ALLIES_TAKE_ARCHERY_FIRE_WOUNDS_INSTEAD_OF_COMPANIONS,
    OPPONENT_FILTERS_YOUR_DRAWS,
    MUST_SURVIVE_SITE_10
}
